spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 15940898
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect